@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> System: Edit Tasks Request

    alt Authorization case

    System --> User: Edit Tasks Response
    User -> System: Edit Tasks POST

        alt succesfull case

        System --> BDD: Edit Task
        System --> User: Succesfull Response

        else

        System --> User: Faillure Response
        end

    else

    System --> User: Unauthorize Response

    end

@enduml