@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> System: Edit User Request
System --> User: Edit UserPage Response

User -> System: Edit User Request POST

alt succesfull case

System -> BDD: User Edit
System --> User: Succesfull Response

else

System --> User: Faillure Response
end
@enduml